accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile_edit/", views.profile_edit, name="profile_edit"),
    path("profile_delete/", views.profile_delete, name="profile_delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("recovery/id/", views.RecoveryIdView.as_view(), name="recovery_id"),
    path("recovery/id/find/", views.ajax_find_id_view, name="ajax_id"),
    # 비밀번호 초기화
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
]

board1/urls.py
from django.urls import path
from . import views

app_name = "board1"

urlpatterns = [
    path("post_list/", views.post_list, name="post_list"),
    path("post_detail/<int:pk>/", views.post_detail, name="post_detail"),
    path(
        "post_list_category/<str:name>/",
        views.post_list_category,
        name="post_list_category",
    ),
    path(
        "post_list_search/<str:search>/",
        views.post_list_search,
        name="post_list_search",
    ),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("new_comment/<int:pk>/", views.comment_new, name="new_comment"),
    path("comment_edit/<int:comment_pk>/", views.comment_edit, name="comment_edit"),
    path(
        "comment_delete/<int:comment_pk>/", views.comment_delete, name="comment_delete"
    ),
]

board2/urls.py
from django.urls import path
from . import views

app_name = "board2"

urlpatterns = [
    path("post_list/", views.post_list, name="post_list"),
    path("post_detail/<int:pk>/", views.post_detail, name="post_detail"),
    path(
        "post_list_category/<str:name>/",
        views.post_list_category,
        name="post_list_category",
    ),
    path(
        "post_list_search/<str:search>/",
        views.post_list_search,
        name="post_list_search",
    ),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("new_comment/<int:pk>/", views.comment_new, name="new_comment"),
    path("comment_edit/<int:comment_pk>/", views.comment_edit, name="comment_edit"),
    path(
        "comment_delete/<int:comment_pk>/", views.comment_delete, name="comment_delete"
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django_pydenticon.views import image as pydenticon_image
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="root"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("board1/", include("board1.urls")),
    path("board2/", include("board2.urls")),
    path("identicon/image/<path:data>/", pydenticon_image, name="pydenticon_image"),
    path("summernote/", include("django_summernote.urls")),
    path("tinymce/", include("tinymce.urls")),
    # 비밀번호 재설정을 위하여 추가된 코드
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


# if settings.DEBUG:  (Holix settings)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/templates/_form.html
{% load bootstrap5 %}


<div class="card">
    <div class="card-header">
        <h3>{{ form_title }}</h3>
    </div>
    <div class="card-body">
        {% if form %}
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary mt-2">
                        {{ submit_label|default:"Submit" }}
                    </button>
                {% endbuttons %}
            </form>
        {% else %}
            <div class="alert alert-danger">
                form 객체를 지정해주세요.
            </div>
        {% endif %}
    </div>
</div>


<script src="https://cdn.tiny.cloud/1/ltkk2wmag3twfcsflbdvyehsx2r7mkv3k5h46avyl67mrt8k/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector:'textarea',
        menubar: false,
        statusbar: false,
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat'
    });
</script>

mysite/templates/_service_form.html
{% load bootstrap5 %}


<div class="card mb-4">
    <div class="card-header">
        <h3 class="fst-italic fw-bold">{{ form_title }}</h3>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="container-md">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3 row">
                            <label for="title" class="col-sm-2 col-form-label">제&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;목</label>
                            <div class="col-sm-10">
                                {% bootstrap_field form.title placeholder=None show_label=False %}
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="phone_number" class="col-sm-2 col-form-label">전화번호</label>
                            <div class="col-sm-3">
                                {% bootstrap_field form.phone_number show_label=False %}
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="category" class="col-sm-2 col-form-label">서&nbsp;비&nbsp;스</label>
                            <div class="col-sm-3">
                                {% bootstrap_field form.category placeholder=None show_label=False %}
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="postcode" class="col-sm-2 col-form-label">우편번호</label>
                            <div class="col-sm-4 d-flex">
                                {% bootstrap_field form.postcode placeholder=None show_label=False %}
                                <input type="button" onclick="sample4_execDaumPostcode()" value="우편번호 찾기" class="ms-5" style="height: 40px">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="roadAddress" class="col-sm-2 col-form-label">도로주소</label>
                            <div class="col-sm-10">
                                {% bootstrap_field form.roadAddress placeholder=None show_label=False %}
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="jibunAddress" class="col-sm-2 col-form-label">지번주소</label>
                            <div class="col-sm-10">
                                {% bootstrap_field form.jibunAddress placeholder=None show_label=False %}
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="detailAddress" class="col-sm-2 col-form-label">상세주소</label>
                            <div class="col-sm-10">
                                {% bootstrap_field form.detailAddress placeholder=None show_label=False %}
                            </div>
                        </div>
                        {% bootstrap_field form.content placeholder=None %}

                        <div class="mb-3" style="display: none">
                            <input type="text" class="" id="sample4_postcode" placeholder="우편번호">
                            <input type="button" class="" onclick="sample4_execDaumPostcode()" value="우편번호 찾기"><br>
                            <input type="text" id="sample4_roadAddress" placeholder="도로명주소">
                            <input type="text" id="sample4_jibunAddress"  placeholder="지번주소">
                            <span id="guide" style="color:#999;display:none"></span>
                            <input type="text" id="sample4_detailAddress" placeholder="상세주소" >
                            <input type="text" id="sample4_extraAddress" placeholder="참고항목"> <br/>
                        </div>

                        <hr>
                            <h5>수집하는 개인정보의 항목</h5>
                            <p>회사는 회원가입, 상담, 서비스 신청 등을 위해 아래와 같은 개인정보를 수집하고 있습니다.</p>
                            <ul>
                                <li><strong>수집항목</strong> : 전화번호, 핸드폰, 이메일, 주소, 남기는말</li>
                                <li><strong>개인정보 수집방법</strong> : 홈페이지</li>
                            </ul>
                            <h5>개인정보의 수집 및 이용목적</h5>
                            <p>회사는 수집한 개인정보를 다음의 목적을 위해 활용합니다.</p>
                            <ul>
                                <li>
                                    <strong>서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금정산</strong>
                                    <p>구매 및 요금 결제, 물품배송 또는 청구지 등 발송</p>
                                </li>
                                <li>
                                    <strong>회원 관리</strong>
                                    <p>회원제 서비스 이용에 따른 본인확인, 개인 식별, 불량회원의 부정 이용 방지와 비인가 사용 방지, 가입 의사 확인, 연령확인</p>
                                </li>
                            </ul>
                            <h5>개인정보의 보유 및 이용기간</h5>
                            <p>회사는 개인정보 수집 및 이용목적이 달성된 후에는 예외 없이 해당 정보를 지체 없이 파기합니다.</p>
                        <hr>

                        <label class="mb-3">
                           <input type="checkbox" name="ck" onClick="checkDisable(this.form)">
                           <span>개인정보 수집·이용에 동의합니다.</span>
                        </label>

                        {% buttons %}
                            <button type="submit" name="bt" class="btn btn-primary" disabled>
                                제출
                            </button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.
    function sample4_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var roadAddr = data.roadAddress; // 도로명 주소 변수
                var extraRoadAddr = ''; // 참고 항목 변수

                // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                    extraRoadAddr += data.bname;
                }
                // 건물명이 있고, 공동주택일 경우 추가한다.
                if(data.buildingName !== '' && data.apartment === 'Y'){
                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                }
                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                if(extraRoadAddr !== ''){
                    extraRoadAddr = ' (' + extraRoadAddr + ')';
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('sample4_postcode').value = data.zonecode;
                document.getElementById("sample4_roadAddress").value = roadAddr;
                document.getElementById("sample4_jibunAddress").value = data.jibunAddress;

                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.
                if(roadAddr !== ''){
                    document.getElementById("sample4_extraAddress").value = extraRoadAddr;
                } else {
                    document.getElementById("sample4_extraAddress").value = '';
                }

                var guideTextBox = document.getElementById("guide");
                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.
                if(data.autoRoadAddress) {
                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;
                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';
                    guideTextBox.style.display = 'block';

                } else if(data.autoJibunAddress) {
                    var expJibunAddr = data.autoJibunAddress;
                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';
                    guideTextBox.style.display = 'block';
                } else {
                    guideTextBox.innerHTML = '';
                    guideTextBox.style.display = 'none';
                }
            }
        }).open();
    }
</script>

<script type="text/javascript">
    function checkDisable(form) {
        if (form.ck.checked == true) {
            form.bt.disabled = false;
        } else {
            form.bt.disabled = true;
        }
    }
</script>

<script src="https://cdn.tiny.cloud/1/ltkk2wmag3twfcsflbdvyehsx2r7mkv3k5h46avyl67mrt8k/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector:"textarea",
        menubar: false,
        statusbar: false,
        toolbar1: "formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat"
        {#height: "330"#}
        {#width: "830"#}
    });
</script>

mysite/templates/about.html
{% extends "layout.html" %}
{% load bootstrap5 static%}



{% block content %}
    {% include "navbar.html" %}

    <div class="container text-center">
        <div class="row">
            <section>
                <div class="container mt-4">
                    <div class="row">
                        <div class="col-lg-8" >
                            <h1>안녕하세요. 소방인 강휘주입니다.</h1>
                            <br/>
                            <p class="lead">
                                소방과 관련된 일을 좋아합니다. <br/>
                                소방관으로 업을 삼고, 퇴근 후에는 소방인으로서의 제2의 삶을 준비 중입니다.
                            </p>

                            <ul>
                                <li>WORK EXPERIENCE</li>
                                <ul>
                                    <li>청와대 국가위기관리센터 (21.3 ~ )</li>
                                    <li>경기도 안전관리실 (18. 3. ~ 19. 6)</li>
                                    <li>경기도 소방재난본부 (16. 7. ~ 18. 2)</li>
                                    <li>제20기 소방간부후보생 교육(14. 3 ~ 15. 3)</li>
                                    <li>제44기 경기도소방공채(08. 1 ~ 14. 2)</li>
                                </ul>
                                <br>

                                <li>LICENSE</li>
                                <ul>
                                    <li>소방기술사(2020)</li>
                                    <li>소방시설관리사(2018)</li>
                                    <li>소방설비기사(2015)</li>
                                </ul>
                            </ul>
                        </div>
                        <div class="col-lg-4">
                            <img class="img-fluid" src="{% static "img/family.jpg" %}">
                        </div>
                    </div>
                </div>
            </section>

            <section class="bg-light margin-for-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h1>PORTFOLIO</h1>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card">
                                <img class="card-img-top" src="{% static "img/국가직.jpg" %}">
                                <div class="card-body">
                                    <h5 class="card-title">국가직 후 1년</h5>
                                    <p>국가직 후 소방공무원의 처우개선 등 달라진 점을 알아봅니다.</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="card">
                                <img class="card-img-top" src="{% static "img/소방법.jfif" %}">
                                <div class="card-body">
                                    <h5 class="card-title">소방관계법령</h5>
                                    <p>2021년 새롭게 바뀌는 소방(안전)과 관련된 법령 모음집입니다.</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="card">
                                <img class="card-img-top" src="{% static "img/홍보.jpg" %}">
                                <div class="card-body" >
                                    <h5 class="card-title">소방홍보동영상</h5>
                                    <p>안전과 관련하여 꼭 필요한 소방 동영상을 홍보합니다.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>

        </div>
    </div>
    {% include "footer.html" %}

{% endblock content %}

mysite/templates/footer.html
{% load static %}

<!-- Footer-->
<footer class="py-4 mt-2 bg-dark" style="font-size: 15px">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static "startbootstrap-blog-home-gh-pages/js/scripts.js" %}"></script>

mysite/templates/index.html
{% extends "layout.html" %}
{% load bootstrap5 static%}



{% block content %}
    {% include "navbar.html" %}
    <div class="container text-center">
        <div class="row">
            <div class="col-12">
                <a href="{% url "accounts:login" %}">
                    <img src="{% static "img/city-g311bc573d_1920.jpg" %}" class="card-img-top" alt="Django">
                </a>
            </div>
{#            <div class="col">#}
{#                <img src="{% static "img/bootstrap-social-logo.png" %}" class="card-img-top" alt="" height="300px" width="300px">#}
{#            </div>#}
{#            <div class="col">#}
{#                <img src="{% static "img/anaconda.png" %}" class="card-img-top" alt="" height="300px" width="300px">#}
{#            </div>#}
        </div>
    </div>
    {% include "footer.html" %}

{% endblock content %}

mysite/templates/layout.html
{% load bootstrap5 static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "startbootstrap-blog-home-gh-pages/assets/favicon.ico" %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "startbootstrap-blog-home-gh-pages/css/styles.css" %}" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/a33698b627.js" crossorigin="anonymous"></script>
        <!-- JQuery -->
        <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    </head>

    <body>
        <!-- Messages-->
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <span class="fst-italic fw-bold" STYLE="font-size: large">
                        {{ message | safe }}
                    </span>
                </div>
            {% endfor %}
        {% endif %}

        <!-- Page content-->
        {% block content %}

        {% endblock content %}
    </body>

</html>

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
    <div class="container">
        <a class="navbar-brand" href="/" style="color: black">Fire Protection</a>
        <button class="navbar-toggler bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="/" style="color: black">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "about" %}" style="color: black">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "blog:post_list" %}" style="color: black">Blog</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">
                         Board
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url "board1:post_list" %}">자유게시판</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url "board2:post_list" %}">소방서비스</a></li>
                    </ul>
                </li>
            </ul>
            {% if not user.is_active %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-right-to-bracket" style="font-size: 20px; color: black"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url "accounts:login" %}">로그인</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">비밀번호 찾기</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url "accounts:signup" %}">회원가입</a></li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">
                        <img class="rounded-circle me-1" src="{{ user.avatar_url }}" alt="pydenticon_image" style="height: 32px; width: 32px"/>
                        <span class="text-muted"> {{ user }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url "accounts:profile_edit" %}">회원정보수정</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url "accounts:profile_delete" %}">회원탈퇴</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url "accounts:logout" %}">로그아웃</a></li>
                    </ul>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>







{#<nav class="navbar navbar-expand-lg bg-light">#}
{#    <div class="container-fluid" style="font-size: 20px">#}
{#        <a class="navbar-brand ms-5 ps-5" href="/" style="color: black;">Fire Protection</a>#}
{#        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarScroll">#}
{#            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" style="color: black" aria-current="page" href="/">Home</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" style="color: black" aria-current="page" href="{% url "about" %}">About</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" style="color: black;" href="{% url "blog:post_list" %}">Blog</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">#}
{#                         Board#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a class="dropdown-item" href="{% url "board1:post_list" %}">자유게시판</a></li>#}
{#                        <li><hr class="dropdown-divider"></li>#}
{#                        <li><a class="dropdown-item" href="{% url "board2:post_list" %}">소방서비스</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#            </ul>#}
{#            {% if not user.is_active %}#}
{#                <ul class="navbar-nav me-5 pe-5">#}
{#                    <li class="nav-item d-flex"><a class="nav-link float-end" style="color: black;" href="{% url "accounts:login" %}">Login</a></li>#}
{#                </ul>#}
{#                <ul class="navbar-nav me-5 pe-5">#}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">#}
{#                            <i class="fa-solid fa-right-to-bracket" style="font-size: 20px"></i>#}
{#                        </a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a class="dropdown-item" href="{% url "accounts:login" %}">로그인</a></li>#}
{#                            <li><hr class="dropdown-divider"></li>#}
{#                            <li><a class="dropdown-item" href="#">비밀번호 찾기</a></li>#}
{#                            <li><hr class="dropdown-divider"></li>#}
{#                            <li><a class="dropdown-item" href="{% url "accounts:signup" %}">회원가입</a></li>#}
{#                        </ul>#}
{#                    </li>#}
{#                </ul>#}
{#            {% else %}#}
{#                <ul class="navbar-nav me-5 pe-5">#}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">#}
{#                            <img class="rounded-circle me-1" src="{{ user.avatar_url }}" alt="pydenticon_image" style="height: 32px; width: 32px"/>#}
{#                            <span class="text-muted"> {{ user }}</span>#}
{#                        </a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a class="dropdown-item" href="{% url "accounts:profile_edit" %}">회원정보수정</a></li>#}
{#                            <li><hr class="dropdown-divider"></li>#}
{#                            <li><a class="dropdown-item" href="{% url "accounts:profile_delete" %}">회원탈퇴</a></li>#}
{#                            <li><hr class="dropdown-divider"></li>#}
{#                            <li><a class="dropdown-item" href="{% url "accounts:logout" %}">로그아웃</a></li>#}
{#                        </ul>#}
{#                    </li>#}
{#                </ul>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{#</nav>#}