accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile_edit/", views.profile_edit, name="profile_edit"),
    path("profile_delete/", views.profile_delete, name="profile_delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("recovery/id/", views.RecoveryIdView.as_view(), name="recovery_id"),
    path("recovery/id/find/", views.ajax_find_id_view, name="ajax_id"),
    # 비밀번호 초기화
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
]

board1/urls.py
from django.urls import path
from . import views

app_name = "board1"

urlpatterns = [
    path("post_list/", views.post_list, name="post_list"),
    path("post_detail/<int:pk>/", views.post_detail, name="post_detail"),
    path(
        "post_list_category/<str:name>/",
        views.post_list_category,
        name="post_list_category",
    ),
    path(
        "post_list_search/<str:search>/",
        views.post_list_search,
        name="post_list_search",
    ),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("new_comment/<int:pk>/", views.comment_new, name="new_comment"),
    path("comment_edit/<int:comment_pk>/", views.comment_edit, name="comment_edit"),
    path(
        "comment_delete/<int:comment_pk>/", views.comment_delete, name="comment_delete"
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django_pydenticon.views import image as pydenticon_image
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="root"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("board1/", include("board1.urls")),
    path("board2/", include("board2.urls")),
    path("identicon/image/<path:data>/", pydenticon_image, name="pydenticon_image"),
    path("summernote/", include("django_summernote.urls")),
    path("tinymce/", include("tinymce.urls")),
    # 비밀번호 재설정을 위하여 추가된 코드
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


# if settings.DEBUG:  (Holix settings)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
import os.path, re
from django.db import models
from django.conf import settings
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/blog/post_list_tag/{}/".format(self.name)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = HTMLField()
    head_image = models.ImageField(upload_to="blog/images/%Y/%m/%d", blank=True)
    head_image_thumbnail = ImageSpecField(
        source="head_image",  # 원본 ImageField 명
        processors=[Thumbnail(850, 350)],  # 처리할 작업목록
        format="JPEG",  # 최종 저장 포맷
        options={"quality": 60},
    )  # 저장 옵션
    file_upload = models.FileField(upload_to="blog/files/%Y/%m%d", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
    )
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return "custom Post object({})".format(self.id)

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.pk])

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split(".")[-1]

    def extract_tag_list(self):
        pattern = r"#([a-zA-Z\dㄱ-힣]+)"
        content = self.content.replace(" ", "")
        tag_name_list = re.findall(pattern, content)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    class Meta:
        ordering = ["-id"]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return "{}::{}".format(self.author, self.message)

    def get_absolute_url(self):
        return f"{self.post.get_absolute_url()}#comment-{self.pk}"

    # def get_avatar_url(self): Todo pydenticon 구현 후
    #     if self.author.socialaccount_set.exists():
    #         return self.author.socialaccount_set.first().get_avatar_url()
    #     else:
    #         return f'https://doitdjango.com/avatar/id/106/31c7242a73e4f345/svg/{self.author.email}'

blog/forms.py
from django import forms
from .models import Post, Comment
from django_summernote.widgets import SummernoteWidget
from tinymce.widgets import TinyMCE


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "head_image", "file_upload", "category"]
        # widgets = {
        #     "content": TinyMCE(
        #         # attrs={"summernote": {"width": "50%", "height": "400px"}}
        #     ),
        # }

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields["content"].widget.attrs = {
            # "placeholder": "본문에 #을 이용하여 태그를 사용해 보세요",
            "rows": 15,
            "cols": 60,
        }

        self.fields["title"].label = "제목"
        self.fields["content"].label = "내용"
        self.fields["head_image"].label = "이미지업로드"
        self.fields["file_upload"].label = "파일업로드"
        self.fields["category"].label = "카테고리"


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["message"].widget.attrs = {
            "placeholder": "메세지를 입력해 주세요",
            "rows": 3,
            "cols": 60,
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm


def post_list(request):
    query = Post.objects.all()
    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    # try:
    #     page_obj = paginator.page(page)
    # except PageNotAnInteger:
    #     page = 1
    #     page_obj = paginator.page(page)
    # except EmptyPage:
    #     page = paginator.num_pages
    #     page_obj = paginator.page(page)

    return render(
        request,
        "blog/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


def post_list_category(request, slug):
    if slug != "기 타":
        query = Post.objects.filter(category__name__contains=slug)
    else:
        query = Post.objects.filter(category=None)

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    return render(
        request,
        "blog/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "slug": slug,
        },
    )


def post_list_search(request, search):
    query = Post.objects.filter(
        Q(title__icontains=search) | Q(tag__name__icontains=search)
    )

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    return render(
        request,
        "blog/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "search": search,
        },
    )


def post_list_tag(request, tag):
    query = Post.objects.filter(tag__name__icontains=tag)

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 2, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    return render(
        request,
        "blog/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "tag": tag,
        },
    )


# @login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()
    comment_form = CommentForm()
    return render(
        request,
        "blog/post_detail.html",
        {
            "post": post,
            "comment_form": comment_form,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


@login_required
def post_new(request):
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag.add(*post.extract_tag_list())
            return redirect("blog:post_detail", post.pk)
    else:
        form = PostForm()

    return render(
        request,
        "blog/post_new.html",
        {
            "form": form,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


@login_required
def post_update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)

        if request.user != post.author:
            messages.warning(request, "수정권한이 없습니다.")
            return redirect(post)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.tag.add(*post.extract_tag_list())
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = PostForm(instance=post)

    return render(
        request,
        "blog/post_update.html",
        {
            "form": form,
            "post": post,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated and request.user == post.author:
        post.delete()
        messages.add_message(request, messages.SUCCESS, "포스트를 삭제했습니다.")
        return redirect("blog:post_list")
    else:
        messages.warning(request, "삭제할 권한이 없습니다.")


def comment_new(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()
                return redirect("blog:post_detail", post.pk)
        else:
            comment_form = CommentForm()
    else:
        raise PermissionDenied

    return redirect(
        request,
        "blog/comment_form.html",
        {
            "comment_form": comment_form,
            "post": post,
        },
    )


def comment_edit(request, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        post = comment.post

        if request.method == "POST":
            comment_form = CommentForm(request.POST, instance=comment)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()
                return redirect(post.get_absolute_url())
        else:
            comment_form = CommentForm(instance=comment)
    else:
        raise PermissionDenied

    return render(
        request,
        "blog/comment_edit.html",
        {
            "comment_form": comment_form,
            "comment": comment,
        },
    )


@login_required
def comment_delete(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        messages.success(request, "댓글을 삭제했습니다.")
        return redirect(comment.post.get_absolute_url())
    else:
        raise PermissionDenied

blog/templates/blog/Post_delete_modal.html
{#<!-- Button trigger modal -->#}
{#<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">#}
{#  Launch demo modal#}
{#</button>#}

<!-- Modal -->
<div class="modal fade" id="PostDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="PostDeleteModal">포스트 삭제</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span class="fst-italic">정말 삭제하시겠습니까?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{% url "blog:post_delete" post.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/comment_delete_modal.html
<!-- Modal -->
<div class="modal fade" id="CommentDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="CommentDeleteModal">댓글 삭제</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span class="fst-italic">정말 삭제하시겠습니까?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{% url "blog:comment_delete" comment.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/comment_edit.html
{% extends "layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <section class="mb-5">
                    <div class="card bg-light">
                        <div class="card-header">
                            <strong>메세지 수정</strong>
                        </div>
                        <div class="card-body">
                            <!-- Comment form-->
                            <form class="mb-3" method="POST" enctype="multipart/form-data" action="{% url "blog:comment_edit" comment.pk %}">
                                {% csrf_token %}
                                {% bootstrap_form comment_form layout="inline" %}
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
                                    {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/comment_form.html
{% load bootstrap5 thumbnail %}

<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-header">
            Leave a Comment
        </div>
        {% if user.is_authenticated %}
            <div class="card-body">
                <!-- Comment form-->
                <form class="mb-3" method="POST" enctype="multipart/form-data" action="{% url "blog:new_comment" post.pk%}">
                    {% csrf_token %}
                    {% bootstrap_form comment_form layout="inline" %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
                        {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
                    </div>
                </form>
                {% if post.comment_set.exists %}
                    {% for comment in post.comment_set.all %}
                        <!-- Comment with nested comments-->
                        <div class="d-flex mb-4 mt-4">
                            <!-- Parent comment-->
                            <div class="flex-shrink-0">
                                <img class="rounded-circle" src="{{ comment.author.avatar_url }}" alt="pydenticon_image" style="height: 60px; width: 60px"/>
                            </div>
                            <div class="ms-3">
                                <div class="fw-bold d-flex"> {{ comment.author }} &nbsp;&nbsp;&nbsp;&nbsp;
                                    {% if comment.created_at == comment.updated_at %}
                                        <small class="text-muted">{{ comment.created_at | date:"Y.m.d H:i"}}</small>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {% else %}
                                        <small class="text-muted">{{ comment.updated_at | date:"Y-m-d H:i"}}</small>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {% endif %}
                                    {% if user.is_authenticated and comment.author == user %}
{#                                        <a role="button" class="btn btn-sm btn-outline-primary" style="font-size: 1.5px" href="{% url "blog:comment_edit" comment.pk %}">수정</a>&nbsp;#}
{#                                        <i class="fa-solid fa-delete-left" role="button" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</i>#}
{#                                        <a role="button" class="btn btn-sm btn-outline-danger" style="font-size: 1.5px;" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</a>&nbsp;#}
                                        <i class="fa-solid fa-delete-left mt-1" role="button" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal"></i>
                                        {% include "blog/comment_delete_modal.html" %}
                                    {% endif %}
                                </div>
                                <p class="mt-1">{{ comment.message | linebreaks }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        {% else %}
             <div class="card-body">
                <a role="button" class="btn btn-outline-dark d-grid" href="{% url "accounts:login" %}" data-toggle="" data-target="#">
                    <strong class="text-muted">Log in and leave a comment</strong>
                </a>
             </div>
        {% endif %}
    </div>
</section>

blog/templates/blog/post_base.html
{% extends "layout.html" %}
{% load bootstrap5 %}

{% block content %}

{% include "navbar.html" %}

<!-- Page header with logo and tagline-->
<header class="py-3 bg-white border-bottom mb-4">
    <div class="container">
        <div class="text-center my-3">
            <h2>블로그에 오신것을 환영합니다.
                {% if slug %}
                    <span class=""> ({{ slug }}) </span>
                {% elif search %}
                    <span class=""> (Search) </span>
                {% elif tag %}
                    <span class=""> (Tag) </span>
                {% endif %}
            </h2>
            <br>
            <p class="lead">
                <span class="fw-bold fst-italic">"소방에 관련된 정보를 신속하게 제공합니다.!" </span>
                {% if user.is_superuser %}
                    <a href="{% url "blog:post_new" %}">
                        <i class="fa-sharp fa-solid fa-pen-nib" style="font-size: x-large"></i></a>
                {% endif %}
            </p>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">

            {% block semi_content %}

            {% endblock semi_content %}

        </div>
        {% include "blog/side_widgets.html" %}
    </div>
</div>

{% include "footer.html" %}

    <style type="text/css">
        a { text-decoration:none; color: black }
    </style>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/post_base.html"%}
{% load bootstrap5 humanize %}


    {% block semi_content %}

        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-2">
                <!-- Post title-->
                <h3 class="mb-1">{{ post.title }}</h3>
                <div class="d-flex text-muted mt-3">
                    <div class="flex-grow-1">
                        <span class="badge rounded-pill bg-light" style="color: black; font-size: 14px">
                            <img class="rounded-circle me-1" src="{{ post.author.avatar_url }}" alt="pydenticon_image" style="height: 32px; width: 32px"/>
                            {{ post.author }}
                        </span>
                    </div>
                    <div>
                        <span class="justify-content-end" style="font-size: 14px">Posted on {{ post.created_at | date:"Y-m-d" }} </span>
                    </div>
                </div>
                <br>
{#                <hr class="btn-outline-dark">#}

                <!-- Post categories-->
                <a class="badge bg-secondary text-decoration-none link-light me-1 mt-1" style="font-size: small;" href="{% url "blog:post_list" %}"> 목록 </a>
                {% if user.is_authenticated and post.author == request.user %}
                    <a class="badge bg-secondary text-decoration-none link-light me-1" style="font-size: small" href="{% url "blog:post_update" post.pk %}"> 수정</a>
                    <a type="button" class="badge bg-secondary text-decoration-none link-light me-1" style="font-size: small" data-bs-toggle="modal" data-bs-target="#PostDeleteModal"> 삭제</a>
                    {% include "blog/Post_delete_modal.html" %}
                {% endif %}
            </header>
            <!-- Preview image figure-->
                {% if post.head_image %}
                    <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="head_image" /></figure>
                {% else %}
                    <figure class="mb-4"><img class="img-fluid rounded" src="https://picsum.photos/850/350/?blur" alt="piscum_image" /></figure>
                {% endif %}
            <!-- Post content-->
            <section class="mb-2 fw-lighter lh-lg">
                {{ post.content | safe }}
            </section>
            {% if post.tag.exists %}
                <i class="fas fa-tags"></i>
                {% for tag in post.tag.all %}
                    <a href="{{ tag.get_absolute_url }}">
                        <span class="badge rounded-pill bg-light" style="color: black">{{ tag }}</span>
                    </a>
                {% endfor %}
            {% endif %}
            <br>
            <br>
            <section class="mb-5">
                {% if post.file_upload %}
                    <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>
                        Download :&nbsp;
                        {% if post.get_file_ext == "csv" %}
                            <i class="fa-solid fa-file-csv"></i>
                        {% elif post.get_file_ext == "xlsx" or post.get_file_ext == "xls" %}
                            <i class="fa-solid fa-file-excel"></i>
                        {% elif post.get_file_ext == "docx" or post.get_file_ext == "doc" %}
                            <i class="fa-solid fa-file-word"></i>
                        {% else %}
                            <i class="fa-solid fa-file"></i>
                        {% endif %}
                        {{ post.get_file_name }}
                    </a>
                {% endif %}
            </section>
        </article>
        <!-- Comments section-->
            {% include "blog/comment_form.html" %}

    {% endblock semi_content %}

blog/templates/blog/side_widgets.html
{% load bootstrap5 %}

<!-- Side widgets-->
<div class="col-lg-4">
    <!-- Search widget-->
    <div class="card mb-4">
        <div class="card-header">Search</div>
        <div class="card-body">
            <div class="input-group">
                <label for="search-input"></label><input class="form-control" type="text" placeholder="Enter search term..." id="search-input"/>
                <button class="btn btn-secondary" id="button-search" type="button" onclick="searchPost();">Go!</button>
            </div>
        </div>
    </div>

    <!-- Categories widget-->
    <div class="card mb-4">
        <div class="card-header">Categories</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-2">
                        <li>
                            <a class="text-muted" href="{% url "blog:post_list" %}"> 전 체 <span class="float-sm-end">({{ total_category_count }})</span></a>
                        </li>
                    </ul>
                </div>
                {% for category in categories %}
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-2">
                            <li>
                                <a class="text-muted" href="{% url "blog:post_list_category" category.slug %}">{{ category.slug }} <span class="float-sm-end">({{ category.post_set.count }})</span></a>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-2">
                        <li>
                            <a class="text-muted" href="{% url "blog:post_list_category" "기 타" %}"> 기 타 <span class="float-sm-end">({{ no_category_count }})</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function searchPost(){
        let searchValue = document.getElementById("search-input").value.trim();
        if (searchValue.length > 1) {
            location.href = "/blog/post_list_search/" + searchValue + "/";
        }
        else {
            alert("검색어(" + searchValue + ")가 너무 짧습니다.")
        }
    }

    document.getElementById("search-input").addEventListener("keydown", function(e)
        {
            if(e.key === "Enter"){
                searchPost()
            }
        });
</script>