accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile_edit/", views.profile_edit, name="profile_edit"),
    path("profile_delete/", views.profile_delete, name="profile_delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("recovery/id/", views.RecoveryIdView.as_view(), name="recovery_id"),
    path("recovery/id/find/", views.ajax_find_id_view, name="ajax_id"),
    # 비밀번호 초기화
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
]

board2/urls.py
from django.urls import path
from . import views

app_name = "board2"

urlpatterns = [
    path("post_list/", views.post_list, name="post_list"),
    path("post_detail/<int:pk>/", views.post_detail, name="post_detail"),
    path(
        "post_list_category/<str:name>/",
        views.post_list_category,
        name="post_list_category",
    ),
    path(
        "post_list_search/<str:search>/",
        views.post_list_search,
        name="post_list_search",
    ),
    path("post_new/", views.post_new, name="post_new"),
    path("post_update/<int:pk>/", views.post_update, name="post_update"),
    path("post_delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("new_comment/<int:pk>/", views.comment_new, name="new_comment"),
    path("comment_edit/<int:comment_pk>/", views.comment_edit, name="comment_edit"),
    path(
        "comment_delete/<int:comment_pk>/", views.comment_delete, name="comment_delete"
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django_pydenticon.views import image as pydenticon_image
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="root"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("board1/", include("board1.urls")),
    path("board2/", include("board2.urls")),
    path("identicon/image/<path:data>/", pydenticon_image, name="pydenticon_image"),
    path("summernote/", include("django_summernote.urls")),
    path("tinymce/", include("tinymce.urls")),
    # 비밀번호 재설정을 위하여 추가된 코드
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


# if settings.DEBUG:  (Holix settings)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board2/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.conf import settings
from django.urls import reverse
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="board2_author_set",
    )
    title = models.CharField(max_length=50)
    content = HTMLField()
    phone_number = models.CharField(
        max_length=13,
        validators=[RegexValidator(r"^010-?[1-9]\d{3}-?\d{4}$")],
    )
    postcode = models.CharField(max_length=10)
    roadAddress = models.CharField(max_length=50)
    jibunAddress = models.CharField(max_length=50)
    detailAddress = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ["-id"]

    def get_absolute_url(self):
        return reverse("board2:post_detail", args=[self.pk])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="board2_my_author_set",
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return "{}::{}".format(self.author, self.message)

    def get_absolute_url(self):
        return f"{self.post.get_absolute_url()}#comment-{self.pk}"

board2/forms.py
from django import forms
from .models import Post, Comment
from django_summernote.widgets import SummernoteWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "category",
            "phone_number",
            "content",
            "postcode",
            "roadAddress",
            "jibunAddress",
            "detailAddress",
        ]

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields["postcode"].widget.attrs = {
            "id": "sample4_postcode",
        }
        self.fields["roadAddress"].widget.attrs = {
            "id": "sample4_roadAddress",
        }
        self.fields["jibunAddress"].widget.attrs = {
            "id": "sample4_jibunAddress",
        }
        self.fields["detailAddress"].widget.attrs = {
            "id": "sample4_detailAddress",
        }
        self.fields["phone_number"].widget.attrs = {
            "placeholder": "예시)010-9999-9999",
        }

        # self.fields["title"].label = "제목"
        # self.fields["phone_number"].label = "전화번호"
        # self.fields["category"].label = "서비스 선택"
        # self.fields["roadAddress"].label = "도로명주소"
        # self.fields["jibunAddress"].label = "지번주소"
        # self.fields["detailAddress"].label = "상세주소"
        self.fields["content"].label = "남기는말"


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["message"].widget.attrs = {
            "placeholder": "메세지를 입력해 주세요",
            "rows": 3,
            "cols": 60,
        }

board2/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Category, Comment
from .forms import CommentForm, PostForm
from datetime import timedelta, datetime
from django.contrib import messages


def post_list(request):
    query = Post.objects.all()
    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 10, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()
    diff_time = datetime.now() - timedelta(hours=24)

    return render(
        request,
        "board2/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "diff_time": diff_time,
        },
    )


def post_list_category(request, name):
    if name != "기 타":
        query = Post.objects.filter(category__name__icontains=name)
    else:
        query = Post.objects.filter(category=None)

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 10, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()
    diff_time = datetime.now() - timedelta(hours=24)

    return render(
        request,
        "board2/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "name": name,
            "diff_time": diff_time,
        },
    )


def post_list_search(request, search):
    query = Post.objects.filter(
        Q(title__icontains=search) | Q(content__icontains=search)
    )

    page = int(request.GET.get("page", 1))  # 두번째 인자 : 없을 시 디폴트 값
    paginator = Paginator(query, 10, allow_empty_first_page=True)
    page_obj = paginator.page(page)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()
    diff_time = datetime.now() - timedelta(hours=24)

    return render(
        request,
        "board2/post_list.html",
        {
            "post_list": query,
            "page_obj": page_obj,
            "paginator": paginator,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
            "search": search,
            "diff_time": diff_time,
        },
    )


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()
    comment_form = CommentForm()

    if request.user.is_superuser:
        pass
    elif not request.user == post.author:  # 중요
        messages.warning(request, "접근권한이 없습니다.")
        return redirect("board2:post_list")

    return render(
        request,
        "board2/post_detail.html",
        {
            "post": post,
            "comment_form": comment_form,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


@login_required
def post_new(request):
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.postcode = request.POST.get("postcode", False)
            # post.roadAddress = request.POST.get("road", False)
            # post.jibunAddress = request.POST.get("jibun", False)
            # post.detailAddress = request.POST.get("detail", False)
            post.save()
            return redirect("board2:post_detail", post.pk)
    else:
        form = PostForm()

    return render(
        request,
        "board2/post_new.html",
        {
            "form": form,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


@login_required
def post_update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    total_category_post_count = Post.objects.all().count()
    no_category_post_count = Post.objects.filter(category=None).count()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if request.user != post.author:
            messages.warning(request, "수정권한이 없습니다.")
            return redirect(post)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post)

    return render(
        request,
        "board2/post_update.html",
        {
            "form": form,
            "post": post,
            "categories": categories,
            "total_category_count": total_category_post_count,
            "no_category_count": no_category_post_count,
        },
    )


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated and request.user == post.author:
        post.delete()
        messages.add_message(request, messages.SUCCESS, "포스트를 삭제했습니다.")
        return redirect("board2:post_list")
    else:
        messages.warning(request, "삭제할 권한이 없습니다.")


def comment_new(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()
                return redirect("board2:post_detail", post.pk)
        else:
            comment_form = CommentForm()
    else:
        raise PermissionDenied

    return redirect(
        request,
        "board2/comment_form.html",
        {
            "comment_form": comment_form,
            "post": post,
        },
    )


def comment_edit(request, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        post = comment.post

        if request.method == "POST":
            comment_form = CommentForm(request.POST, instance=comment)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()
                return redirect(post.get_absolute_url())
        else:
            comment_form = CommentForm(instance=comment)
    else:
        raise PermissionDenied

    return render(
        request,
        "board2/comment_edit.html",
        {
            "comment_form": comment_form,
            "comment": comment,
        },
    )


@login_required
def comment_delete(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        messages.success(request, "댓글을 삭제했습니다.")
        return redirect(comment.post.get_absolute_url())
    else:
        raise PermissionDenied

board2/templates/board2/Post_delete_modal.html
<!-- Modal -->
<div class="modal fade" id="PostDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="PostDeleteModal">포스트 삭제</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span class="fst-italic">정말 삭제하시겠습니까?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{% url "board2:post_delete" post.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>

board2/templates/board2/comment_delete_modal.html
<!-- Modal -->
<div class="modal fade" id="CommentDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="CommentDeleteModal">댓글 삭제</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span class="fst-italic">정말 삭제하시겠습니까?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="{% url "board2:comment_delete" comment.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>

board2/templates/board2/comment_form.html
{% load bootstrap5 thumbnail %}

<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-header">
            Leave a Comment
        </div>
        {% if user.is_authenticated %}
            <div class="card-body">
                <!-- Comment form-->
                <form class="mb-3" method="POST" enctype="multipart/form-data" action="{% url "board2:new_comment" post.pk%}">
                    {% csrf_token %}
                    {% bootstrap_form comment_form layout="inline" %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
                        {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
                    </div>
                </form>
                {% if post.comment_set.exists %}
                    {% for comment in post.comment_set.all %}
                        <!-- Comment with nested comments-->
                        <div class="d-flex mb-4 mt-4">
                            <!-- Parent comment-->
                            <div class="flex-shrink-0">
                                <img class="rounded-circle" src="{{ comment.author.avatar_url }}" alt="pydenticon_image" style="height: 60px; width: 60px"/>
                            </div>
                            <div class="ms-3">
                                <div class="fw-bold d-flex"> {{ comment.author }} &nbsp;&nbsp;&nbsp;&nbsp;
                                    {% if comment.created_at == comment.updated_at %}
                                        <small class="text-muted">{{ comment.created_at | date:"Y.m.d H:i" }}</small>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {% else %}
                                        <small class="text-muted">{{ comment.updated_at | date:"Y.m.d H:i" }}</small>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {% endif %}
                                    {% if user.is_authenticated and comment.author == user %}
{#                                        <a role="button" class="btn btn-sm btn-outline-primary" style="font-size: 1.5px" href="{% url "board2:comment_edit" comment.pk %}">수정</a>&nbsp;#}
{#                                        <a role="button" class="btn btn-sm btn-outline-danger" style="font-size: 1.5px;" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal">삭제</a>&nbsp;#}
                                        <i class="fa-solid fa-delete-left mt-1" role="button" data-bs-toggle="modal" data-bs-target="#CommentDeleteModal"></i>
                                        {% include "board2/comment_delete_modal.html" %}
                                    {% endif %}
                                </div>
                                <p class="mt-1">{{ comment.message | linebreaks }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        {% else %}
             <div class="card-body">
                <a role="button" class="btn btn-outline-dark d-grid" href="{% url "accounts:login" %}" data-toggle="" data-target="#">
                    <strong class="text-muted">Log in and leave a comment</strong>
                </a>
             </div>
        {% endif %}
    </div>
</section>

board2/templates/board2/post_base.html
{% extends "layout.html" %}
{% load bootstrap5 %}

{% block content %}

{% include "navbar.html" %}
<!-- Page header with logo and tagline-->
<header class="py-3 bg-white border-bottom mb-4">
    <div class="container">
        <div class="text-center my-3">
            <h1 class="fw-bolder"> 소방서비스
                {% if name %}
                    <span class=""> ({{ name }}) </span>
                {% elif search %}
                    <span class=""> (Search) </span>
                {% else %}
                {% endif %}
            </h1>
            <br>
            <p class="lead mb-0 fw-bold">
                <span class="fst-italic">"소방서비스에 대해여 문의해 주세요!" </span>
            </p>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">
            <div class="alert alert-danger text-lg-center" role="alert">
                <h4 class="alert-heading">Well done!</h4>
                <p>이 페이지는 작동기능점검 등 소방서비스를 제공하기 위해 만든 페이지입니다.</p>
                <hr>
                <p class="mb-0">개인정보는 작성자 및 관리자만 열람할 수 있습니다. 글을 작성하시면 곧 관리자가 연락드리겠습니다!.</p>
            </div>

            {% block semi_content %}

            {% endblock semi_content %}
        </div>
        {% include "board2/side_widgets.html" %}
    </div>
</div>

{% include "footer.html" %}

    <style type="text/css">
        a { text-decoration:none; color: black }
    </style>

{% endblock content %}

board2/templates/board2/post_detail.html
{% extends "board2/post_base.html" %}
{% load bootstrap5 %}

    {% block semi_content %}

        <div class="card">
            <div class="card-header" style="background-color: white">
                <div class="d-flex text-muted mt-3">
                    <div class="flex-grow-1">
                        <!-- Post title-->
                        <h3 class="mb-1">{{ post.title }}</h3>
                    </div>
                    <div>
                        <a class="badge bg-secondary text-decoration-none link-light me-1 mt-1" style="font-size: small;" href="{% url "board2:post_list" %}"> 목록 </a>
                        {% if user.is_authenticated and post.author == request.user %}
                            <a class="badge bg-secondary text-decoration-none link-light me-1" style="font-size: small" href="{% url "board2:post_update" post.pk %}"> 수정</a>
                            <a type="button" class="badge bg-secondary text-decoration-none link-light me-1" style="font-size: small" data-bs-toggle="modal" data-bs-target="#PostDeleteModal"> 삭제</a>
                            {% include "board2/Post_delete_modal.html" %}
                        {% endif %}
                    </div>
                </div>
                <div class="d-flex text-muted mt-3">
                    <div class="flex-grow-1">
                        <span class="badge rounded-pill bg-light text-muted" style="color: black; font-size: 14px">
                            <img class="rounded-circle me-1" src="{{ post.author.avatar_url }}" alt="pydenticon_image" style="height: 32px; width: 32px"/>
                            {{ post.author }}
                        </span>
                    </div>
                    <div>
                        <span class="justify-content-end" style="font-size: 14px">Posted on {{ post.created_at | date:"Y-m-d" }} </span>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <!-- Post content-->
                <section class="mb-2 lh-lg">
                    전화번호 : {{ post.phone_number }} <br>
                    우편번호 : {{ post.postcode }} <br>
                    도로주소 : {{ post.roadAddress }} <br>
                    지번주소 : {{ post.jibunAddress }} <br>
                    상세주소 : {{ post.detailAddress }}
                </section>
            </div>
            <div class="card-footer">
                <hr>
                   {{ post.content | safe }}
                <hr>
            </div>
        </div>
        <br>
        <!-- Comments section-->
        {% include "board2/comment_form.html" %}

    {% endblock semi_content %}

board2/templates/board2/post_list.html
{% extends "board2/post_base.html" %}
{% load bootstrap5 %}

    {% block semi_content %}

        <table class="table table-hover">
            <thead class="table-light text-lg-center">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" style="width: 500px">제 목</th>
                    <th scope="col">작성자</th>
                    <th scope="col">작성일</th>
                    <th scope="col">댓글</th>
                </tr>
            </thead>

            <tbody>
                {% if post_list %}
                    {% for post in page_obj %}
                        <tr>
                            <th scope="row" class="text-lg-center">{{ post.pk }} &nbsp;</th>
                            <td>
                                <span class="fw-bold">
                                    {% if post.category == None %}
                                        [기 타] &nbsp;
                                    {% else %}
                                        [{{ post.category }}] &nbsp;
                                    {% endif %}
                                </span>
                                <a href="{% url "board2:post_detail" post.pk %}">{{ post.title }}</a>
                                {% if post.created_at >= diff_time %}
                                    &nbsp;<i class="fa-regular fa-comment-dots" style="font-size: 5px; color: red"> new</i>
                                {% endif %}
                            </td>
                            <td class="text-lg-center">
                                <span class="badge rounded-pill bg-light" style="color: black">
                                    <img class="rounded-circle me-1" src="{{ post.author.avatar_url }}" alt="pydenticon_image" style="height: 24px; width: 24px"/>
                                    {{ post.author }}
                                </span>
                            </td>
                            <td class="text-lg-center">
                                <span class="text-muted" style="font-size: 14px">{{ post.created_at |  date:"Y-m-d" }}</span>
                            </td>
                            <td class="text-lg-center">
                                {{ post.comment_set.all.count }}
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <div class="d-flex">
            <div class="flex-grow-1">
                {% bootstrap_pagination page_obj %}
                <style> ul{ justify-content: center } </style>
            </div>
            <div>
               {% if user.is_authenticated %}
                    <a class="btn btn-secondary mb-3 justify-content-end" style="font-size: small" role="button" href="{% url "board2:post_new" %}">
                        <i class="fa-solid fa-pen"></i> &nbsp;글쓰기
                    </a>
                {% endif %}
            </div>
        </div>

    {% endblock semi_content %}

board2/templates/board2/post_new.html
{% extends "board2/post_base.html" %}
{% load bootstrap5 %}


{% block semi_content %}
    {% include "_service_form.html" with form_title="새 포스트 작성" %}
    <br>
{% endblock semi_content %}

board2/templates/board2/post_update.html
{% extends "board2/post_base.html" %}
{% load bootstrap5 %}


{% block semi_content %}
    {% include "_service_form.html" with form_title="포스트 수정" %}
    <br>
{% endblock semi_content %}

board2/templates/board2/side_widgets.html
{% load bootstrap5 %}

<!-- Side widgets-->
<div class="col-lg-4">
    <!-- Search widget-->
    <div class="card mb-4">
        <div class="card-header">Search</div>
        <div class="card-body">
            <div class="input-group">
                <label for="search-input"></label><input class="form-control" type="text" placeholder="Enter search term..." id="search-input"/>
                <button class="btn btn-secondary" id="button-search" type="button" onclick="searchPost();">Go!</button>
            </div>
        </div>
    </div>

    <!-- Categories widget-->
    <div class="card mb-4">
        <div class="card-header">Categories</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-2">
                        <li>
                            <a class="text-muted" href="{% url "board2:post_list" %}"> 전 체 <span class="float-sm-end">({{ total_category_count }})</span></a>
                        </li>
                    </ul>
                </div>
                {% for category in categories %}
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-2">
                            <li>
                                <a class="text-muted" href="{% url "board2:post_list_category" category.name %}">{{ category.name }} <span class="float-sm-end">({{ category.post_set.count }})</span></a>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-2">
                        <li>
                            <a class="text-muted" href="{% url "board2:post_list_category" "기 타" %}"> 기 타 <span class="float-sm-end">({{ no_category_count }})</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function searchPost(){
        let searchValue = document.getElementById("search-input").value.trim();
        if (searchValue.length > 1) {
            location.href = "/board2/post_list_search/" + searchValue + "/";
        }
        else {
            alert("검색어(" + searchValue + ")가 너무 짧습니다.")
        }
    }

    document.getElementById("search-input").addEventListener("keydown", function(e)
        {
            if(e.key === "Enter"){
                searchPost()
            }
        });
</script>